{
 "title": "Home",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Current temperature",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    { "expr": "pihome_temperature" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "pihome_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "pihome_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Current humidity",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 8 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    { "expr": "pihome_humidity" }
   ]
  },
  {
   "title": "Movement",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pihome_movement{}[1m])",
     "legendFormat": "Movement"
    }
   ]
  },
  {
   "title": "Network Devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pihome_network_device) by (mac,hostname,vendor)",
     "legendFormat": "{{mac}}({{hostname}}, {{vendor}})"
    }
   ]
  },
  {
   "title": "Bluetooth Devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pihome_bluetooth_device) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}